# Generated by Django 2.2 on 2021-08-29 17:59

import TestApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, validators=[TestApp.models.validateLengthGreaterThanTwo])),
                ('last_name', models.CharField(max_length=45, validators=[TestApp.models.validateLengthGreaterThanTwo])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
            ],
        ),
    ]
