# Generated by Django 2.2 on 2021-08-29 20:51

import TestApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(error_messages={'required': 'please enter'}, max_length=45, validators=[TestApp.models.validateLengthGreaterThanTwo]),
        ),
    ]
